values:
  deploymentName: my-app-deployment-beta
  serviceName: my-app-service-beta
  replicas: 2
  image:
    repository: docker.io/nginx
    tag: 1.29.5
    digest: ""
    pullPolicy: IfNotPresent
  service:
    port: 8081
  env:
    MY_ENV_VAR: beta-value
    ANOTHER_VAR: beta-another-value
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
  virtualService:
    enabled: true
    hosts:
      - "beta-app.example.com"
    gateways:
      - "istio-system/beta-gateway"
